name: Check
on:
  push:
    branches: [ dev ]
  pull_request:
    branches:
      - master
      - dev
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Cache node_modules
      uses: actions/cache@v1
      env:
        cache-name: hexo-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
    - run: yarn install
    - run: yarn run build